version: '3.8'

services:
  wordpress:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

volumes:
  db_data: